apiVersion: bespin.dev/v1
kind: OrganizationPolicy
metadata:
  name: zlu-folder-orgpolicy
spec:
  constraints:
  - constraint: constraints/compute.storageResourceUseRestrictions
    listPolicy:
      disallowedValues:
        - under:folders/138920254001
    booleanPolicy:
      enforced: true
  - constraint: constraints/iam.disableServiceAccountCreation
    booleanPolicy:
      enforced: true
  - constraint: constraints/compute.disableSerialPortAccess
    booleanPolicy:
      enforced: true
